# URL de connexion à MySQL 
spring.datasource.url=jdbc:mysql://localhost:3306/xmlproject_db?useSSL=false&serverTimezone=UTC

# Identifiants MySQL
spring.datasource.username=root
spring.datasource.password=

# Hibernate crée/met à jour les tables automatiquement
spring.jpa.hibernate.ddl-auto=update

# Affiche les requêtes SQL dans la console 
spring.jpa.show-sql=true

# Dialecte MySQL pour Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Nom de l'application
spring.application.name=xml-project